stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  split_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_local_dir/train.csv
      - artifacts/split_local_dir/test.csv
  train_data:
    cmd: python src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/raw_local_dir/data.csv
      - src/utils/all_utils.py
      - config/config.yaml
    params:
      - base.random_state
      - base.test_size
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio
    outs:
      - artifacts/model_local_dir/Elasticnet.model