#Here we talk about data source

data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  artifcats_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv


  split_local_dir: split_local_dir
  train_file: train.csv
  test_file : test.csv

  model_local_dir: model_local_dir
  model_file: Elasticnet.model





